baseURL = "https://generdoc.netlify.app"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableGitInfo = true
enableRobotsTXT = true
theme = ["github.com/onweru/compose"]
title = "Generdoc"
[markup.goldmark.extensions]
typographer = false
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = false
style = "monokai"
tabWidth = 2
[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2
[[menu.main]]
name = "Docs"
url = "docs/"
weight = 2
[[menu.main]]
name = "Example"
url = "https://docs.neuralvibes.com"
weight = 3
[params]
author = "Weru"
enableDarkMode = true
repo = "https://github.com/onweru/compose"
searchPlaceholder = "Search the docs ..."
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
[params.logo]
darkMode = "compose-light.svg"
lightMode = "compose.svg"
[params.source]
icon = "github.svg"
name = "GitHub"
url = "https://github.com/onweru/compose/"
